Explicitly build in release mode
Builds are failing with protobuf 3.20.1 at runtime with
ImportError: libimp_npctransport.so.0: undefined symbol:
_ZN6google8protobuf8internal16InternalMetadataD1Ev

This appears to be because protobuf was built in release
mode (with NDEBUG defined) but we are (perhaps) building
in debug mode (without NDEBUG). Relates
conda-forge/ctng-compiler-activation-feedstock#73.